sudo: required
services: 
  - docker
    
    
before_install:
  - docker build -t KristinaDe/docker-react -f Dockerfile.dev .

script:
  - docker run KristinaDe/docker-react npm run test -- --coverage

